### PR TITLE
Allow double-quotes as literal terms

### PR DESCRIPTION
**Pull request by scoheb**

### CODE REVIEW

**Comment by scoheb** [comment]
Thanks!
Can we create a release with this fix?

**Comment by mjeremym** [comment]
Sure,

Minor release.

Try to night, if not this weekend

Going to release 2.0 for the upgrade to Jeromq 0.4 and JMS 2.1 but it may take a wee bit longer.

Regards
Jeremy

**Comment by scoheb** [comment]
Minor release would be great! Tx

**Comment by scoheb** [comment]
Can you please let me know when it is available please? I need to release https://github.com/jenkinsci/jms-messaging-plugin/pull/21/
Thanks!

**Comment by mjeremym** [comment]
Will do. Need to be done at home. Blocked at work

Jeremy

**Comment by mjeremym** [comment]
done

**Comment by scoheb** [comment]
Seems like this release is a bit different.
I am now getting this while build my project:

```
[INFO] Restricted to JDK 1.7 yet org.zeromq:jeromq-jms:jar:1.1.1-RELEASE:compile contains org/zeromq/jms/protocol/redelivery/ZmqRedeliveryPolicy.class targeted to JDK 1.8
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: org.zeromq:jeromq-jms:jar:1.1.1-RELEASE

```
Can this be rebuild with JDK 1.7?

**Comment by mjeremym** [comment]
Let me look at it tonight

I had switch to java 8 for version 2 and swapped branches in the ide.
Let me do it work lest haste this time
Sorry
Jeremy

**Comment by mjeremym** [comment]
Hello,

I have fix up my POM (to include the enforcer). I can only assume it was caused by my hard coding to JDK 1.8 for the tools and console.

I get no EnforceBytecodeVerison errors, which I did get before the fix.

It has been pushed to maven central as 1.1.1 again.

regards
Jeremy

**Comment by scoheb** [comment]
I will give it a try shortly! thanks!

**Comment by scoheb** [comment]
Seems like the maven repos that I use for dependencies have cached the old 1.1.1 release. I see the correct one here though: https://repo.maven.apache.org/maven2/org/zeromq/jeromq-jms/1.1.1-RELEASE/jeromq-jms-1.1.1-RELEASE.jar

Would you have able to release 1.1.2 so that the repos are refreshed? The only change would be the pom version.

Thanks!

**Comment by mjeremym** [comment]
Sure
I'll do it tonight
Jeremy

**Comment by mjeremym** [comment]
OK 1.1.2 has been released.

Let me know if you have any issues.

regards
Jeremy

**Comment by scoheb** [comment]
Still not seeing it here: http://repo.jenkins-ci.org/public/org/zeromq/jeromq-jms/ or here http://repo.maven.apache.org/maven2/org/zeromq/jeromq-jms/

I will wait and see if it appears.

**Comment by mjeremym** [comment]
odd, it on nexus as released

https://oss.sonatype.org/#nexus-search;quick~jeromq-jms <https://oss.sonatype.org/#nexus-search;quick~jeromq-jms>

<dependency>
  <groupId>org.zeromq</groupId>
  <artifactId>jeromq-jms</artifactId>
  <version>1.1.2-RELEASE</version>
</dependency>

I’ll check later. On the weekend it was fast. Not on maven central yet

Jeremy

**Comment by scoheb** [comment]
All good now!

**Pull request merged**
